const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94775546547"
const SESSION_ID = "PRABATH-MD~cz8SRBQT#L-IRbn7fvixDwJBRdlRDfukKmk45oLyfVE0pcD8Sncg"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
